// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCOegJIN_YGhES3HpOhmkTmTmcKvPMjf8',
    appId: '1:765939599786:web:21024cf7fddd3496d883d3',
    messagingSenderId: '765939599786',
    projectId: 'unishare-e85ad',
    authDomain: 'unishare-e85ad.firebaseapp.com',
    storageBucket: 'unishare-e85ad.firebasestorage.app',
    measurementId: 'G-ND864SPYWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoqT7ta7AOuRAtztW321Tm7Imd4WjGBJA',
    appId: '1:765939599786:android:d5fd3ee23d4e88dbd883d3',
    messagingSenderId: '765939599786',
    projectId: 'unishare-e85ad',
    storageBucket: 'unishare-e85ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUH6jF0Uuwo-jgtDo3EbwkFoa7uJRJd5Q',
    appId: '1:765939599786:ios:84a587997ae75d2dd883d3',
    messagingSenderId: '765939599786',
    projectId: 'unishare-e85ad',
    storageBucket: 'unishare-e85ad.firebasestorage.app',
    iosBundleId: 'com.example.unishare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUH6jF0Uuwo-jgtDo3EbwkFoa7uJRJd5Q',
    appId: '1:765939599786:ios:84a587997ae75d2dd883d3',
    messagingSenderId: '765939599786',
    projectId: 'unishare-e85ad',
    storageBucket: 'unishare-e85ad.firebasestorage.app',
    iosBundleId: 'com.example.unishare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCOegJIN_YGhES3HpOhmkTmTmcKvPMjf8',
    appId: '1:765939599786:web:a67510de30761b85d883d3',
    messagingSenderId: '765939599786',
    projectId: 'unishare-e85ad',
    authDomain: 'unishare-e85ad.firebaseapp.com',
    storageBucket: 'unishare-e85ad.firebasestorage.app',
    measurementId: 'G-HNWY9V2S28',
  );
}
